### ISSUE TITLE
Question regarding a standard approach

### ISSUE THREAD

**Issue by mxcl** [TimOliver/TORoundedButton#10]
I have been generating rounded-stretchable images for years (dynamically, with code) to set as the `backgroundImage` of my `UIButton`s to the same goal as your library.

This also has the advantage that I get highlight-colorization for free.

It wasn't clear after reading your README why I should instead use your library.

Thanks for your time!

**Comment by TimOliver** [comment]
Oh wow! Hi Max! I saw your Quora post about Google, and I was recently looking at your Patreon in terms of what sets the standard for supporting open source developers. It's an honour to hear from you! :)

Okay, thanks for the question. I'll try my best to explain my idea behind this library here.

If you're already dynamically generating stretchable rounded images, then that's more or less the same here. This library basically has two modes it operates under: when it needs to be transparent, or when it can be opaque.

In cases where it's fine to be opaque (eg, the button will be placed on a white background, so its background can also be white), then it does exactly the same as what you said. It uses Core Graphics to dynamically generate a resizable rounded rectangle image. This logic is encapsulated inside the class, and uses an `isDirty` mechanism to batch when it needs to recreate those images (eg, if the background colour suddenly changed) in the next `layoutSubviews` call.

For cases where it absolutely needs to be transparent (eg, it's being placed over translucent content), then it uses a completely different approach. Instead, the images are discarded, and the background image view is just tinted the appropriate colour. I then used the `CALayer.cornerRadius` API to then mask the entire view with rounded corners.

I did it this way for a specific reason. I talked to a Core Animation engineer at the labs at WWDC18 and they told me that thanks to the way Metal doesn't need to do so many context swaps, the `cornerRadius` effect on Metal devices is "basically free". Since this means I can create the effect without needing to generate a transparent image that would require layer blending ([keeping it all green](https://twitter.com/TimOliverAU/status/1124105432258293760)), this would be slightly more performant than simply generating a rounded rectangle image with a clear background.

In regards to why it's a `UIControl` and not a `UIButton` subclass, the main things that killed it for me was not getting public access to the background image so I could control it for the animation. I ended up deciding it would be better to just keep the `UIControl` logic, but I could implement the display logic as custom on top, and this would be far better than trying to fight `UIButton`'s implicit behaviours.

But to sum all that up in why you should use my library: if you already have a method that works for you, then you probably don't need to use it. For the most part, my biggest goal here was to just be able to bundle that dynamic rounded rectangle image generation code into a re-usable class, but to also add a few niceties here and there.

Maybe this is completely over-engineering/prematurely optimizing a solution. But since I'm gearing up to build an app that will be using a lot of rounded buttons, and since these kinds of buttons are becoming such a fundamental component of iOS, I wanted something really concrete I could rely on for a long time.

Does that answer your question? Let me know if there's anything else I might need to clarify.

Thanks for the issue!

**Comment by mxcl** [comment]
Thanks for the detailed answer!

This certainly makes sense:

> In regards to why it's a UIControl and not a UIButton subclass, the main things that killed it for me was not getting public access to the background image so I could control it for the animation.

`UIButton` is pretty difficult to animate. Your code is clean, so I'll certainly be looking to this package in the future, should I have difficulty in this area. I may just import it anyway to save messing around with rounded-stretchables like I do currently.

**Comment by TimOliver** [comment]
Awesome! I'm really happy to hear I was able to clarify that and that you might consider using it in future. If you ever have any other questions, please feel free to ask anytime!

In the meantime, I'll re-examine my README and see if I can make the goals of this library a bit more clear in there.

Thanks and take care!
