### ISSUE TITLE
Carthage build end up in /static folder?

### ISSUE THREAD

**Issue by danqing** [TimOliver/TORoundedButton#18]
While every other framework builds directly into the build folder, somehow this framework ends up in the build/static folder. Any way it can be consistent with others? Thanks!

<img width="281" alt="Screen Shot 2019-06-15 at 1 01 48 PM" src="https://user-images.githubusercontent.com/5134133/59547218-c1f86700-8f6d-11e9-9ade-df3cac6d1d95.png">

**Comment by danqing** [comment]
Also not directly relevant, but your `TOCropViewController` (great library!) can be imported as `CropViewController` in Swift. Any chance this can be imported as `RoundedButton` for consistency? Thanks!

**Comment by TimOliver** [comment]
Hi @danqing!

Yes, that makes sense. I've set the framework to be static instead of dynamic. Dynamic frameworks add additional time to the launch time of the app (https://medium.com/@avijeet.dutta13/ios-app-launch-time-analysis-and-optimization-a219ee81447c), so for this particular framework, considering it's literally only one class, adding it as a dynamic framework seems like an incredibly bad trade-off.

If anything, I'd recommend you review those other frameworks in your app and see if they could be made static instead. :)

Also thanks! I'm glad you like `TOCropViewController`. Ahhh, I mean, in Swift, it's already implemented in code as `RoundedButton`. In my crop view controller's case, I actually made a separate Swift implementation class that properly wrapped all of the Objective-C interfaces, so it made sense to make a wholly separate `.framework`, dropping the prefix.

I'm not too sure about here though. It doesn't make too much sense to wrap this one since its interface is much more simple. I mean, I could easily make a separate framework build target called `RoundedButton.framework`, but I wonder if having multiple frameworks in Carthage is a good idea.

Let me know what you think. If that can be solved by just making another framework target, I'm happy to do that. :)

**Comment by danqing** [comment]
Ah I see. Didn't know that - thanks for the explanation!

Actually it turns out that I need to subclass it, since I'm using Carthage and it doesn't support the @IB stuff. I'll just call my subclass `RoundedButton` ;)

**Comment by krzyzanowskim** [comment]
The built framework should have a header to be importable, shouldn't it?

![Screenshot 2019-06-24 at 23 59 41](https://user-images.githubusercontent.com/758033/60054882-28068c00-96dc-11e9-9688-3c1c107ddfd4.png)

**Comment by TimOliver** [comment]
@krzyzanowskim  Blimey! You're completely right Marcin! I have no idea how I missed that! Well spotted! 😅

Okay, it's fixed now (https://github.com/TimOliver/TORoundedButton/pull/23). Cutting a new framework release now.

Thank you so much for telling me!
