### ISSUE TITLE
Why it performance better than UIButton?

### ISSUE THREAD

**Issue by huahuahu** [TimOliver/TORoundedButton#30]
I saw this in the readme

> most developers will achieve this look by simply giving a `UIButton` a solid background, and then using the Core Animation `cornerRadius` API to round the corners. 

> As simple as this is, this is gross overkill for a lot of circumstances in which you'd use a buttonI

In the implementation, I saw `cornerRadius` API 
```
- (void)setCornerRadius:(CGFloat)cornerRadius
{
    // Make sure the corner radius doesn't match
    if (fabs(cornerRadius - _cornerRadius) < FLT_EPSILON) {
        return;
    }
    
    _cornerRadius = cornerRadius;
    self.backgroundView.layer.cornerRadius = _cornerRadius;
    [self setNeedsLayout];
}
```
So what's the difference?
please help me out

**Comment by TimOliver** [comment]
Hi @huahuahu!

I need to update the README. I went to WWDC this year and showed this UI to Apple engineers. They confirmed that since iOS adopted Metal, using `cornerRadius` in specific circumstances is the most performant way of rendering rounded corners. I've adjusted the library to how they recommended it to get the best performance, which is mainly making sure there is no sub-view content in the view being rounded.

Previously it also had an opaque mode where the background was rendered in Core Graphics, but the Apple engineers all agreed that that is actually more memory and processor intensive.

So I already took care of setting up the most performant way to round corners in this library, and I've also added better animations when the button is tapped too. For those reasons, I would recommend this over modifying `UIButton` each time.

But if you want to apply `cornerRadius` to `UIButton`, you can. Just make sure to test in the simulator that when you enable `Off-screen rendered`, the corners don't turn yellow or else you're not getting the Metal speed benefits.

**Comment by huahuahu** [comment]
> Hi @huahuahu!
> 
> I need to update the README. I went to WWDC this year and showed this UI to Apple engineers. They confirmed that since iOS adopted Metal, using `cornerRadius` in specific circumstances is the most performant way of rendering rounded corners. I've adjusted the library to how they recommended it to get the best performance, which is mainly making sure there is no sub-view content in the view being rounded.
> 
> Previously it also had an opaque mode where the background was rendered in Core Graphics, but the Apple engineers all agreed that that is actually more memory and processor intensive.
> 
> So I already took care of setting up the most performant way to round corners in this library, and I've also added better animations when the button is tapped too. For those reasons, I would recommend this over modifying `UIButton` each time.
> 
> But if you want to apply `cornerRadius` to `UIButton`, you can. Just make sure to test in the simulator that when you enable `Off-screen rendered`, the corners don't turn yellow or else you're not getting the Metal speed benefits.

Thanks for the explaination. It seems Apple finally solved this problem
