### ISSUE TITLE
How to set transparent background with text?

### ISSUE THREAD

**Issue by wiencheck** [TimOliver/TORoundedButton#31]
I noticed a strange behavior when setting colors for the button. What I'm doing is simply
```
            button.tintColor = theme.primary.withAlphaComponent(0.2)
            button.textColor = theme.primary
```
and label ends up with a strange frame behind it. See the screenshot
![IMG_0403](https://user-images.githubusercontent.com/25985996/68082666-bffd4a80-fe1f-11e9-8d35-e2d1339a1028.PNG)

**Comment by TimOliver** [comment]
Hi @wiencheck!

Hmm, that's an interesting effect. The text label inherits the tint colour of the control, in order to set its own background and avoid un-necessary blending. If the background element has a different alpha value, this is what would cause that effect.

It'll probably just be a matter of adding some custom logic to make the background color of the text label clear if the tint color doesn't have 100% full alpha.

If you'd like to add that as a PR, it should be really simple. :)

Hope that helped!

**Comment by TimOliver** [comment]
So in the interim time since this issue was opened, I added the ability to set `UIColor` instances that don't have 1.0 `alpha` values as the background colour with the label itself updating to match.

This should hopefully resolve this issue now.
