### ISSUE TITLE
Tapping the button sends the gesture to the responder below

### ISSUE THREAD

**Issue by wiencheck** [TimOliver/TORoundedButton#32]
I have added a `UITapGestureRecognizer` to my `UIViewController's` view and noticed that tapping on the `RoundedButton` embedeed in that view is also registered by the gesture recognizer. I don't think it's a desired effect

**Comment by TimOliver** [comment]
Hi @wiencheck! I'm so sorry for the late reply. 😅

Um. As best as I can tell, this should be expected behaviour. This library doesn't do any custom touch calculations. It's based off `UIControl` and subscribe directly to the touch events that class generates. Since this library doesn't operate on the gesture recogniser level at all, I think this is sort of out of scope.

This is a problem that the classic `UIButton` API would have as well. There are some potential answers on Stack Overflow that might potentially help: https://stackoverflow.com/questions/3344341/uibutton-inside-a-view-that-has-a-uitapgesturerecognizer

Good luck!
